export enum CacheKey {
  'ASSETS' = 'assets-api-assets',
  'AUTH' = 'assets-api-auth',
  'CATEGORIES' = 'assets-api-categories',
  'DEPRECATES' = 'assets-api-deprecates',
  'ISSUES' = 'assets-api-issues',
  'LIQUIDATES' = 'assets-api-liquidates',
  'PROPERTIES' = 'assets-api-properties',
  'RECEIPTS' = 'assets-api-receipts',
  'RECOVERIES' = 'assets-api-recoveries',
  'REGIONS' = 'assets-api-regions',
  'STORES' = 'assets-api-stores',
  'TRANSFERS' = 'assets-api-transfers',
  'VENDORS' = 'assets-api-vendors',
}
