version: '3.1'
services:
  rabbitmq:
    container_name: hcmue-rabbitmq-service
    image: rabbitmq:3.10-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - net-hcmue
    volumes:
      - ./home:/var/lib/rabbitmq
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    restart: 'always'
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 500M

  background-queue:
    container_name: hcmue-background-queue-service
    image: hoanglong1011/hcmue-background:1.1
    environment:
      - NODE_ENV=development
      - MYSQL_HOST=103.154.176.80
      - MYSQL_PORT=3306
      - MYSQL_DATABASE_NAME=hcmue_rlsv_v1
      - MYSQL_USERNAME=uat
      - MYSQL_PASSWORD=Uatvtcode@2022
      
      - MONGODB_URL=mongodb://adminYouth:adminYouth2022@103.154.176.80:27072/youth-app-product?authMechanism=DEFAULT&authSource=youth-app-product
      
      - MONGODB_HOST=103.154.176.80
      - MONGODB_PORT=27072
      - MONGODB_USERNAME=adminYouth
      - MONGODB_PASSWORD=adminYouth2022
      - MOGODB_DATABASE_NAME=youth-app-product

      - BACKGROUND_JOB_SERVICE_HOST=rabbitmq
      - BACKGROUND_JOB_SERVICE_PORT=5672

      - COMPOSER_SERVICE_HOST=rabbitmq
      - COMPOSER_SERVICE_PORT=5672
      
      - MAX_TIMES=3
    networks:
      - net-hcmue
    volumes:
      - ./logs:/opt/app/logs
    restart: 'always'
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      rollback_config:
        parallelism: 2
        delay: 10s
        failure_action: pause
        order: stop-first
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback
        order: stop-first
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  composer-queue:
    container_name: hcmue-composer-queue-service
    image: hoanglong1011/hcmue-composer:1.1
    environment:
      - NODE_ENV=development
      - MYSQL_HOST=103.154.176.80
      - MYSQL_PORT=3306
      - MYSQL_DATABASE_NAME=hcmue_rlsv_v1
      - MYSQL_USERNAME=uat
      - MYSQL_PASSWORD=Uatvtcode@2022
      
      - MONGODB_URL=mongodb://adminYouth:adminYouth2022@103.154.176.80:27072/youth-app-product?authMechanism=DEFAULT&authSource=youth-app-product
      
      - MONGODB_HOST=103.154.176.80
      - MONGODB_PORT=27072
      - MONGODB_USERNAME=adminYouth
      - MONGODB_PASSWORD=adminYouth2022
      - MOGODB_DATABASE_NAME=youth-app-product

      - BACKGROUND_JOB_SERVICE_HOST=rabbitmq
      - BACKGROUND_JOB_SERVICE_PORT=5672

      - COMPOSER_SERVICE_HOST=rabbitmq
      - COMPOSER_SERVICE_PORT=5672
      
      - ITEMS_PER_PAGE=100
      - MAX_TIMES=3
    networks:
      - net-hcmue
    volumes:
      - ./logs:/opt/app/logs
    restart: 'always'
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      rollback_config:
        parallelism: 2
        delay: 10s
        failure_action: pause
        order: stop-first
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback
        order: stop-first
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  schedule:
    container_name: hcmue-schedule-service
    image: hoanglong1011/hcmue-schedule:1.1
    environment:
      - NODE_ENV=development      
      - MYSQL_HOST=103.154.176.80
      - MYSQL_PORT=3306
      - MYSQL_DATABASE_NAME=hcmue_rlsv_v1
      - MYSQL_USERNAME=uat
      - MYSQL_PASSWORD=Uatvtcode@2022
      
      - MONGODB_URL=mongodb://adminYouth:adminYouth2022@103.154.176.80:27072/youth-app-product?authMechanism=DEFAULT&authSource=youth-app-product
      
      - MONGODB_HOST=103.154.176.80
      - MONGODB_PORT=27072
      - MONGODB_USERNAME=adminYouth
      - MONGODB_PASSWORD=adminYouth2022
      - MOGODB_DATABASE_NAME=youth-app-product

      - BACKGROUND_JOB_SERVICE_HOST=rabbitmq
      - BACKGROUND_JOB_SERVICE_PORT=5672

      - COMPOSER_SERVICE_HOST=rabbitmq
      - COMPOSER_SERVICE_PORT=5672
      
      - ITEMS_PER_PAGE=100
      
      - GENERATE_CREATE_SHEETS_CRON_JOB_TIME='0 0 0 * * *'
      - UPDATE_STATUS_SHEETS_CRON_JOB_TIME='0 0 0 * * *'
      - UNLINK_FILES_CRON_JOB_TIME='0 0 2 * * *'
    networks:
      - net-hcmue
    volumes:
      - ./logs:/opt/app/logs
    restart: 'always'
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      rollback_config:
        parallelism: 2
        delay: 10s
        failure_action: pause
        order: stop-first
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback
        order: stop-first
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  hcmue:
    # container_name: hcmue-service
    image: hoanglong1011/hcmue:1.1
    environment:
      - NODE_ENV=development
      - MYSQL_HOST=103.154.176.80
      - MYSQL_PORT=3306
      - MYSQL_DATABASE_NAME=hcmue_rlsv
      - MYSQL_USERNAME=uat
      - MYSQL_PASSWORD=Uatvtcode@2022

      - MONGODB_URL=mongodb://adminYouth:adminYouth2022@103.154.176.80:27072/youth-app-product?authMechanism=DEFAULT&authSource=youth-app-product

      - MONGODB_HOST=103.154.176.80
      - MONGODB_PORT=27072
      - MONGODB_USERNAME=adminYouth
      - MONGODB_PASSWORD=adminYouth2022
      - MOGODB_DATABASE_NAME=youth-app-product
    ports:
      - "5099:3000"
    networks:
      - net-hcmue
    volumes:
      - ./logs:/opt/app/logs
      - ./static:/opt/app/static
    restart: 'always'
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      rollback_config:
        parallelism: 2
        delay: 10s
        failure_action: pause
        order: stop-first
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback
        order: stop-first

networks:
  net-hcmue:
    driver: bridge