export enum Configuration {
  MYSQL_TYPE = 'MYSQL_TYPE',
  MYSQL_HOST = 'MYSQL_HOST',
  MYSQL_PORT = 'MYSQL_PORT',
  MYSQL_DATABASE_NAME = 'MYSQL_DATABASE_NAME',
  MYSQL_USERNAME = 'MYSQL_USERNAME',
  MYSQL_PASSWORD = 'MYSQL_PASSWORD',

  MONGODB_URL = 'MONGODB_URL',
  MONGODB_HOST = 'MONGODB_HOST',
  MONGODB_PORT = 'MONGODB_PORT',
  MONGODB_USERNAME = 'MONGODB_USERNAME',
  MONGODB_PASSWORD = 'MONGODB_PASSWORD',
  MOGODB_DATABASE_NAME = 'MOGODB_DATABASE_NAME',

  LOGGING = 'LOGGING',
  LOGGER = 'LOGGER',

  ITEMS_PER_PAGE = 'ITEMS_PER_PAGE',

  MULTER_DEST = 'MULTER_DEST',

  BACKGROUND_JOB_SERVICE_HOST = 'BACKGROUND_JOB_SERVICE_HOST',
  BACKGROUND_JOB_SERVICE_PORT = 'BACKGROUND_JOB_SERVICE_PORT',

  COMPOSER_SERVICE_HOST = 'COMPOSER_SERVICE_HOST',
  COMPOSER_SERVICE_PORT = 'COMPOSER_SERVICE_PORT',

  BACKGROUND_JOB_QUEUE = 'BACKGROUND_JOB_QUEUE',
  COMPOSER_QUEUE = 'COMPOSER_QUEUE',

  GENERATE_CREATE_SHEETS_CRON_JOB_TIME = 'GENERATE_CREATE_SHEETS_CRON_JOB_TIME',
  UNLINK_FILES_CRON_JOB_TIME = 'UNLINK_FILES_CRON_JOB_TIME',
  UPDATE_STATUS_SHEETS_CRON_JOB_TIME = 'UPDATE_STATUS_SHEETS_CRON_JOB_TIME',
}
