export enum Configuration {
  MYSQL_TYPE = 'MYSQL_TYPE',
  MYSQL_HOST = 'MYSQL_HOST',
  MYSQL_PORT = 'MYSQL_PORT',
  MYSQL_DATABASE_NAME = 'MYSQL_DATABASE_NAME',
  MYSQL_USERNAME = 'MYSQL_USERNAME',
  MYSQL_PASSWORD = 'MYSQL_PASSWORD',

  MONGODB_URL = 'MONGODB_URL',
  MONGODB_HOST = 'MONGODB_HOST',
  MONGODB_PORT = 'MONGODB_PORT',
  MONGODB_USERNAME = 'MONGODB_USERNAME',
  MONGODB_PASSWORD = 'MONGODB_PASSWORD',
  MOGODB_DATABASE_NAME = 'MOGODB_DATABASE_NAME',
  LOGGING = 'LOGGING',
  LOGGER = 'LOGGER',
}
