export enum Configuration {
  MYSQL_TYPE = 'MYSQL_TYPE',
  MYSQL_HOST = 'MYSQL_HOST',
  MYSQL_PORT = 'MYSQL_PORT',
  MYSQL_DATABASE_NAME = 'MYSQL_DATABASE_NAME',
  MYSQL_USERNAME = 'MYSQL_USERNAME',
  MYSQL_PASSWORD = 'MYSQL_PASSWORD',

  MONGODB_URL = 'MONGODB_URL',
  MONGODB_HOST = 'MONGODB_HOST',
  MONGODB_PORT = 'MONGODB_PORT',
  MONGODB_USERNAME = 'MONGODB_USERNAME',
  MONGODB_PASSWORD = 'MONGODB_PASSWORD',
  MOGODB_DATABASE_NAME = 'MOGODB_DATABASE_NAME',
  LOGGING = 'LOGGING',
  LOGGER = 'LOGGER',

  ACCESS_SECRET_KEY = 'ACCESS_SECRET_KEY',
  REFRESH_SECRET_KEY = 'REFRESH_SECRET_KEY',
  ACCESS_TOKEN_EXPIRESIN = 'ACCESS_TOKEN_EXPIRESIN',
  REFRESH_TOKEN_EXPIRESIN = 'REFRESH_TOKEN_EXPIRESIN',
  ITEMS_PER_PAGE = 'ITEMS_PER_PAGE',

  BASE_URL = 'BASE_URL',
  FORGOT_PASSWORD_URL = 'FORGOT_PASSWORD_URL',
  FORGOT_PASSWORD_TOKEN_EXPIRESIN = 'FORGOT_PASSWORD_TOKEN_EXPIRESIN',

  STATIC_PATH = 'STATIC_PATH',
  MULTER_DEST = 'MULTER_DEST',
  MAX_FIELD_SIZE_VALUE = 'MAX_FIELD_SIZE_VALUE',
  MAX_FILE_SIZE_NAME = 'MAX_FILE_SIZE_NAME',
  MAX_FILE_SIZE_VALUE = 'MAX_FILE_SIZE_VALUE',
  EXTENSION_NAMES = 'EXTENSION_NAMES',
  EXTENSION_VALUES = 'EXTENSION_VALUES',

  SALT = 'SALT',
  EMAIL_USERNAME = 'EMAIL_USERNAME',
  EMAIL_PASSWORD = 'EMAIL_PASSWORD',

  URL_EXPORT_TEMPLATE_1 = 'URL_EXPORT_TEMPLATE_1',
  URL_EXPORT_TEMPLATE_2 = 'URL_EXPORT_TEMPLATE_2',
  URL_EXPORT_TEMPLATE_3 = 'URL_EXPORT_TEMPLATE_3',
}
