export enum Configuration {
  MYSQL_TYPE = 'MYSQL_TYPE',
  MYSQL_HOST = 'MYSQL_HOST',
  MYSQL_PORT = 'MYSQL_PORT',
  MYSQL_DATABASE_NAME = 'MYSQL_DATABASE_NAME',
  MYSQL_USERNAME = 'MYSQL_USERNAME',
  MYSQL_PASSWORD = 'MYSQL_PASSWORD',

  MONGODB_URL = 'MONGODB_URL',
  MONGODB_HOST = 'MONGODB_HOST',
  MONGODB_PORT = 'MONGODB_PORT',
  MONGODB_USERNAME = 'MONGODB_USERNAME',
  MONGODB_PASSWORD = 'MONGODB_PASSWORD',
  MOGODB_DATABASE_NAME = 'MOGODB_DATABASE_NAME',
  LOGGING = 'LOGGING',
  LOGGER = 'LOGGER',

  ACCESS_SECRET_KEY = 'ACCESS_SECRET_KEY',
  REFRESH_SECRET_KEY = 'REFRESH_SECRET_KEY',
  ACCESS_TOKEN_EXPIRESIN = 'ACCESS_TOKEN_EXPIRESIN',
  REFRESH_TOKEN_EXPIRESIN = 'REFRESH_TOKEN_EXPIRESIN',
  ITEMS_PER_PAGE = 'ITEMS_PER_PAGE',

  MAX_TIMES = 'MAX_TIMES',

  AUTH_MODULE = 'AUTH_MODULE',
  BACKGROUND_JOB_MODULE = 'BACKGROUND_JOB_MODULE',
  COMPOSER_MODULE = 'COMPOSER_MODULE',
  NOTIFICATION_MODULE = 'NOTIFICATION_MODULE',
  REDIS_MODULE = 'REDIS_MODULE',
  SCHEDULE_MODULE = 'SCHEDULE_MODULE',

  OVERFLOW_ARGUMENT = 'OVERFLOW_ARGUMENT',
}
